### ISSUE TITLE
lastest version doesnt seems up to date

### ISSUE THREAD

**Issue by PierreCsn** [arthurrump/versionsof.net#13]
Hello
The latest version of dotnet 6 is 6.09 on your website and 6.11 on microsoft one. it's not updating since mid september.
Any chance you can fix it ?
best regards

**Comment by arthurrump** [comment]
Thanks for the heads up! There were a few small things that needed to be fixed and that somehow fell of my todo list. Once https://github.com/dotnet/core/pull/7978 is merged, it should be updating again.

**Comment by PierreCsn** [comment]
No problem, I ve been using your website flawlessly for a year or something and it was working very well for my puprose.
best regards

**Comment by arthurrump** [comment]
It's up to date again
