### ISSUE TITLE
Dotnet 7 is the latest stable version

### ISSUE THREAD

**Issue by kaffarell** [arthurrump/versionsof.net#14]
* https://dotnet.microsoft.com/en-us/download/dotnet
* release blog post https://devblogs.microsoft.com/dotnet/announcing-dotnet-7/

**Comment by arthurrump** [comment]
Hey @kaffarell, thanks for the notice. There were a few problems that prevented the update from happening, but I was just working on the last one. Things should be up again in a few more minutes.
