### ISSUE TITLE
Channel 8.0 only shows up to Preview 3

### ISSUE THREAD

**Issue by CollinAlpert** [arthurrump/versionsof.net#15]
The [Channel 8.0](https://versionsof.net/core/8.0/) only shows 3 previews, even though 5 have currently been released. I looked through the code and couldn't find a way to fix this via PR, so I assume the site just needs to be rebuilt.

**Comment by arthurrump** [comment]
It's up-to-date again, thanks for the heads-up! Indeed a case of just needing a rebuild; Azure DevOps decided to stop running the scheduled builds again...
